language: node_js

node_js:
  - "8.4.0"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
  - nvm alias default 8.4.0
  - nvm use 8.4.0

install:
  - yarn

script:
  - set -e
  - yarn run lint
  - yarn run compile
  - yarn run test
