branches:
  only:
    - staging
    - production

os: osx
osx_image: xcode8.2

language: node_js
node_js:
  - "8.4.0"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2

install:
  - yarn
  - node ./scripts/distro-download-certs.js

script:
  - yarn relink
  - ./distro.sh

notifications:
  email:
    on_success: never
    on_failure: change
  slack: the-haiku-team:dpd26udXvhWVlvoZTgKDj5jV
