branches:
  only:
    - staging
    - production

os: osx
osx_image: xcode8.3

language: node_js
node_js:
  - "8.4.0"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
  - nvm alias default 8.4.0
  - nvm use 8.4.0

install:
  - yarn

script:
  - node ./scripts/distro-download-certs.js
  - yarn relink
  - ./distro.sh

notifications:
  email:
    on_success: never
    on_failure: change
  slack: the-haiku-team:dpd26udXvhWVlvoZTgKDj5jV
